package relay

import (
	"context"
	"encoding/base64"
	"fmt"
	"sync"
	"time"

	"github.com/SHC-Labs/drift/internal/api"
	"github.com/SHC-Labs/drift/internal/crypto"
	"github.com/SHC-Labs/drift/internal/log"
)

// kekFetchResponse is the wire format from /v1/relay/kek-wrap. Server
// returns the wrapped KEK plus the sender's pubkey so the recipient
// can derive the symmetric wrap key via ECDH.
type kekFetchResponse struct {
	WrappedKEK   string `json:"wrapped_kek"`   // base64 ciphertext
	Nonce        string `json:"nonce"`         // base64
	Tag          string `json:"tag"`           // base64
	SenderPubkey string `json:"sender_pubkey"` // hex
	KEKVersion   int    `json:"kek_version"`
}

// KEKManager owns the org KEK lifecycle: fetch, unwrap, cache,
// surface. The cached KEK lives in memory only; it never hits disk.
// On rotation the server returns a new wrap with an incremented
// kek_version; we re-fetch + re-unwrap.
//
// Mirrors the TS relay's KekManager with simpler semantics: no legacy
// org-key migration path (Sprint 2 v1 doesn't carry over the C.1-C.3
// keystore migration).
type KEKManager struct {
	client *api.Client
	keys   *crypto.ECDHKeyPair

	mu      sync.RWMutex
	current []byte // 32 bytes
	version int
	expiry  time.Time
}

// NewKEKManager builds a manager that fetches + unwraps under the
// given keypair (the relay's own ECDH keypair, generated by
// EnsureKeyPair).
func NewKEKManager(client *api.Client, keys *crypto.ECDHKeyPair) *KEKManager {
	return &KEKManager{client: client, keys: keys}
}

// Get returns the current org KEK, fetching + unwrapping from the
// server on first call or after the cache expires. Caches for 1 hour;
// rotation in the same window forces a re-fetch when the server
// returns a 410 Gone or similar on subsequent operations.
func (m *KEKManager) Get(ctx context.Context) ([]byte, error) {
	m.mu.RLock()
	if m.current != nil && time.Now().Before(m.expiry) {
		out := append([]byte{}, m.current...)
		m.mu.RUnlock()
		return out, nil
	}
	m.mu.RUnlock()

	m.mu.Lock()
	defer m.mu.Unlock()
	// Re-check after acquiring write lock; another goroutine may have
	// raced us and populated the cache.
	if m.current != nil && time.Now().Before(m.expiry) {
		return append([]byte{}, m.current...), nil
	}

	wrapped, err := fetchWrappedKEK(ctx, m.client)
	if err != nil {
		return nil, fmt.Errorf("fetch KEK: %w", err)
	}

	senderPub, err := decodeSenderPubkey(wrapped.SenderPubkey)
	if err != nil {
		return nil, err
	}
	wk, err := decodeWrappedKEK(wrapped)
	if err != nil {
		return nil, err
	}

	kek, err := crypto.UnwrapKEKFrom(wk, m.keys.Priv, senderPub)
	if err != nil {
		return nil, fmt.Errorf("unwrap KEK: %w", err)
	}
	m.current = kek
	m.version = wrapped.KEKVersion
	m.expiry = time.Now().Add(1 * time.Hour)

	log.Info("relay.kek", "unwrapped", map[string]any{
		"version":     wrapped.KEKVersion,
		"fingerprint": crypto.Fingerprint(kek),
	})

	return append([]byte{}, kek...), nil
}

// Invalidate clears the cached KEK. Called when the server returns
// a key-mismatch error on a DEK unwrap, signaling that the KEK
// rotated and the cached version is stale.
func (m *KEKManager) Invalidate() {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.current = nil
	m.expiry = time.Time{}
}

// fetchWrappedKEK calls /v1/relay/kek-wrap to retrieve the wrapped
// KEK for this recipient (the developer identified by the Bearer
// token).
func fetchWrappedKEK(ctx context.Context, c *api.Client) (*kekFetchResponse, error) {
	var resp kekFetchResponse
	if err := c.GetJSON(ctx, "/v1/relay/kek-wrap", &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// decodeWrappedKEK turns the base64 fields from the wire response
// into the byte slices crypto.UnwrapKEKFrom expects.
func decodeWrappedKEK(resp *kekFetchResponse) (*crypto.WrappedKEK, error) {
	wrapped, err := base64.StdEncoding.DecodeString(resp.WrappedKEK)
	if err != nil {
		return nil, fmt.Errorf("decode wrapped_kek: %w", err)
	}
	nonce, err := base64.StdEncoding.DecodeString(resp.Nonce)
	if err != nil {
		return nil, fmt.Errorf("decode nonce: %w", err)
	}
	tag, err := base64.StdEncoding.DecodeString(resp.Tag)
	if err != nil {
		return nil, fmt.Errorf("decode tag: %w", err)
	}
	return &crypto.WrappedKEK{
		Wrapped: wrapped,
		Nonce:   nonce,
		Tag:     tag,
	}, nil
}

// decodeSenderPubkey hex-decodes the sender pubkey. TS relay
// publishes pubkeys as hex; the wire format mirrors that.
func decodeSenderPubkey(hexStr string) ([]byte, error) {
	if hexStr == "" {
		return nil, fmt.Errorf("empty sender pubkey")
	}
	return decodeHexPubkey(hexStr)
}
