package relay

import (
	"context"
	"encoding/base64"
	"fmt"
	"sync"
	"time"

	"github.com/SHC-Labs/drift/internal/api"
	"github.com/SHC-Labs/drift/internal/crypto"
	"github.com/SHC-Labs/drift/internal/log"
)

// kekFetchResponse is the wire format from GET /api/relay/kek-wrap.
// Server returns the wrapped KEK + the sender_developer_id (NOT the
// sender pubkey directly). The recipient looks up the sender's pubkey
// separately via /api/relay/pubkey and runs ECDH against own privkey.
type kekFetchResponse struct {
	ID                   string `json:"id"`
	OrgID                string `json:"org_id"`
	RecipientDeveloperID string `json:"recipient_developer_id"`
	SenderDeveloperID    string `json:"sender_developer_id"`
	KEKVersion           int    `json:"kek_version"`
	WrappedKEK           string `json:"wrapped_kek"` // base64
	Nonce                string `json:"nonce"`       // base64
	Tag                  string `json:"tag"`         // base64
}

// pubkeyListEntry is one item in GET /api/relay/pubkey's response array.
// Used to look up sender pubkey when unwrapping a KEK.
type pubkeyListEntry struct {
	DeveloperID string `json:"developer_id"`
	OrgID       string `json:"org_id"`
	ECDHPubkey  string `json:"ecdh_pubkey"` // base64
	Fingerprint string `json:"fingerprint"`
}

type pubkeyListResponse struct {
	Pubkeys []pubkeyListEntry `json:"pubkeys"`
}

// KEKManager owns the org KEK lifecycle: fetch wrapped, look up sender
// pubkey, ECDH unwrap, cache, surface. The cached KEK lives in memory
// only; never hits disk.
//
// Mirrors the TS relay's KekManager at the wire level.
type KEKManager struct {
	client *api.Client
	keys   *crypto.ECDHKeyPair

	mu      sync.RWMutex
	current []byte // 32 bytes
	version int
	expiry  time.Time
}

// NewKEKManager builds a manager that fetches + unwraps under the
// given keypair (the relay's own ECDH keypair, generated by
// EnsureKeyPair).
func NewKEKManager(client *api.Client, keys *crypto.ECDHKeyPair) *KEKManager {
	return &KEKManager{client: client, keys: keys}
}

// Get returns the current org KEK, fetching + unwrapping from the
// server on first call or after the cache expires. Caches for 1 hour.
func (m *KEKManager) Get(ctx context.Context) ([]byte, error) {
	m.mu.RLock()
	if m.current != nil && time.Now().Before(m.expiry) {
		out := append([]byte{}, m.current...)
		m.mu.RUnlock()
		return out, nil
	}
	m.mu.RUnlock()

	m.mu.Lock()
	defer m.mu.Unlock()
	if m.current != nil && time.Now().Before(m.expiry) {
		return append([]byte{}, m.current...), nil
	}

	wrapped, err := fetchWrappedKEK(ctx, m.client)
	if err != nil {
		return nil, fmt.Errorf("fetch KEK: %w", err)
	}

	senderPub, err := lookupSenderPubkey(ctx, m.client, wrapped.SenderDeveloperID)
	if err != nil {
		return nil, fmt.Errorf("lookup sender pubkey: %w", err)
	}
	wk, err := decodeWrappedKEK(wrapped)
	if err != nil {
		return nil, err
	}

	kek, err := crypto.UnwrapKEKFrom(wk, m.keys.Priv, senderPub)
	if err != nil {
		return nil, fmt.Errorf("unwrap KEK: %w", err)
	}
	m.current = kek
	m.version = wrapped.KEKVersion
	m.expiry = time.Now().Add(1 * time.Hour)

	log.Info("relay.kek", "unwrapped", map[string]any{
		"version":     wrapped.KEKVersion,
		"fingerprint": crypto.Fingerprint(kek),
	})

	return append([]byte{}, kek...), nil
}

// Invalidate clears the cached KEK. Called when the server returns
// a key-mismatch error on a DEK unwrap, signaling that the KEK
// rotated and the cached version is stale.
func (m *KEKManager) Invalidate() {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.current = nil
	m.expiry = time.Time{}
}

// fetchWrappedKEK calls GET /api/relay/kek-wrap to retrieve the
// active wrapped KEK for this developer.
func fetchWrappedKEK(ctx context.Context, c *api.Client) (*kekFetchResponse, error) {
	var resp kekFetchResponse
	if err := c.GetJSON(ctx, "/api/relay/kek-wrap", &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// lookupSenderPubkey calls GET /api/relay/pubkey (org-wide listing)
// and finds the entry for senderDeveloperID. Returns the sender's
// ECDH pubkey bytes for the ECDH unwrap.
func lookupSenderPubkey(ctx context.Context, c *api.Client, senderDeveloperID string) ([]byte, error) {
	var resp pubkeyListResponse
	if err := c.GetJSON(ctx, "/api/relay/pubkey", &resp); err != nil {
		return nil, fmt.Errorf("list pubkeys: %w", err)
	}
	for _, p := range resp.Pubkeys {
		if p.DeveloperID == senderDeveloperID {
			return base64.StdEncoding.DecodeString(p.ECDHPubkey)
		}
	}
	return nil, fmt.Errorf("sender %s pubkey not in org list", senderDeveloperID)
}

// decodeWrappedKEK turns the base64 fields from the wire response
// into the byte slices crypto.UnwrapKEKFrom expects.
func decodeWrappedKEK(resp *kekFetchResponse) (*crypto.WrappedKEK, error) {
	wrapped, err := base64.StdEncoding.DecodeString(resp.WrappedKEK)
	if err != nil {
		return nil, fmt.Errorf("decode wrapped_kek: %w", err)
	}
	nonce, err := base64.StdEncoding.DecodeString(resp.Nonce)
	if err != nil {
		return nil, fmt.Errorf("decode nonce: %w", err)
	}
	tag, err := base64.StdEncoding.DecodeString(resp.Tag)
	if err != nil {
		return nil, fmt.Errorf("decode tag: %w", err)
	}
	return &crypto.WrappedKEK{
		Wrapped: wrapped,
		Nonce:   nonce,
		Tag:     tag,
	}, nil
}
