package ipc

import (
	"crypto/rand"
	"encoding/binary"
	"fmt"

	"github.com/SHC-Labs/drift/internal/config"
)

// EphemeralLow and EphemeralHigh bound the range we pick the relay port
// from. IANA dynamic/private range is 49152-65535; we stay inside that to
// avoid colliding with registered services.
const (
	EphemeralLow  = 49152
	EphemeralHigh = 65535
)

// EnsurePort returns the persisted relay port from ~/.drift/config.json.
// If no port is persisted yet, picks a random one in the IANA dynamic
// range and writes it back. The port is sticky for the install's
// lifetime: once chosen, never changes (even on reinstall).
//
// Random is sourced from crypto/rand, not math/rand, so two installs on
// the same machine generated by parallel `drift install` runs are
// vanishingly unlikely to collide.
//
// Picked-but-conflicting ports get caught at bind time, not here.
// EnsurePort just reserves the customer's port number; the hardened
// bind in BindHardened is what fails loud on conflict.
func EnsurePort() (int, error) {
	cfg, err := config.ReadBinaryConfig()
	if err != nil {
		return 0, fmt.Errorf("read binary config: %w", err)
	}
	if cfg.RelayPort >= EphemeralLow && cfg.RelayPort <= EphemeralHigh {
		return cfg.RelayPort, nil
	}
	port, err := pickRandomPort()
	if err != nil {
		return 0, err
	}
	cfg.RelayPort = port
	if err := config.WriteBinaryConfig(cfg); err != nil {
		return 0, fmt.Errorf("persist relay port: %w", err)
	}
	return port, nil
}

// CurrentPort returns the persisted port WITHOUT writing one if none is
// set. Returns 0 if no port is persisted yet. Used by `drift relay
// status` and `drift doctor` so they don't accidentally write config
// just by reading.
func CurrentPort() (int, error) {
	cfg, err := config.ReadBinaryConfig()
	if err != nil {
		return 0, err
	}
	return cfg.RelayPort, nil
}

// pickRandomPort returns a uniformly random port in [EphemeralLow,
// EphemeralHigh]. crypto/rand source so different installs don't collide
// systematically.
func pickRandomPort() (int, error) {
	span := uint32(EphemeralHigh - EphemeralLow + 1)
	var buf [4]byte
	if _, err := rand.Read(buf[:]); err != nil {
		return 0, fmt.Errorf("read entropy: %w", err)
	}
	u := binary.BigEndian.Uint32(buf[:])
	return EphemeralLow + int(u%span), nil
}
